name: Build and Push Docker Images
run-name: build ${{ github.sha }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push sepe-app Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sepe/app:latest
          platforms: linux/amd64

      - name: Build and push sepe-ui Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./ui
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sepe/ui:latest
          platforms: linux/amd64
